version: '3.8'

services:
  # LiveKit Token Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CLIENT_URL=http://localhost:8080
    env_file:
      - ./config/.env
    volumes:
      - ./server/src:/app/src
      - ./config:/app/config
    command: npm run dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://sip-connect-studio-3.onrender.com/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    environment:
      - VITE_SERVER_URL=https://sip-connect-studio-3.onrender.com
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev
    restart: unless-stopped
    depends_on:
      - server

  # Nginx reverse proxy (optional, for production-like setup)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: pstn-livekit-network
